# Generated by Django 5.2.1 on 2025-05-14 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("provider", models.CharField(max_length=63)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("checkout_url", models.CharField(max_length=255)),
                ("external_id", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["reservation"],
                        name="payments_pa_reserva_0762c2_idx",
                    )
                ],
            },
        ),
    ]
