# Generated by Django 5.2.1 on 2025-05-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="checkout_url",
            field=models.TextField(),
        ),
    ]
