# Generated by Django 5.2.1 on 2025-05-20 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_checkout_url"),
        ("reservations", "0002_reservation_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment",
                to="reservations.reservation",
            ),
        ),
    ]
