services:
  app:
    build:
      context: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - app
    restart: always

  db:
    image: postgres:16-alpine
    volumes:
      - pgdata_theatre_service:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data_theatre_service:/var/lib/pgadmin
    restart: always

  redis:
    image: redis:latest
    volumes:
      - redis_data_theatre_service:/data
    restart:
      always

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart:
      always


volumes:
  pgdata_theatre_service:
  pgadmin_data_theatre_service:
  redis_data_theatre_service:
