# Generated by Django 5.2.1 on 2025-05-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rows", models.PositiveIntegerField()),
                ("seats_in_row", models.PositiveIntegerField()),
                (
                    "theatre_hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="theatre.theatrehall",
                    ),
                ),
            ],
            options={
                "default_related_name": "zones",
            },
        ),
        migrations.CreateModel(
            name="ZonePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_price", models.PositiveBigIntegerField()),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="theatre.performance",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="theatre.zone"
                    ),
                ),
            ],
            options={
                "default_related_name": "zone_prices",
            },
        ),
        migrations.AddField(
            model_name="performance",
            name="zones",
            field=models.ManyToManyField(
                through="theatre.ZonePrice", to="theatre.zone"
            ),
        ),
        migrations.DeleteModel(
            name="TheatreHallZone",
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.UniqueConstraint(
                fields=("name", "theatre_hall"), name="unique_name_theatre_hall"
            ),
        ),
        migrations.AddConstraint(
            model_name="zoneprice",
            constraint=models.UniqueConstraint(
                fields=("zone", "performance"), name="unique_zone_performance"
            ),
        ),
    ]
