# Generated by Django 5.2.1 on 2025-05-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_zone_zoneprice_performance_zones_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveIntegerField()),
                ("seat", models.PositiveIntegerField()),
                ("price", models.PositiveBigIntegerField()),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="theatre.performance",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="theatre.zone",
                    ),
                ),
            ],
            options={
                "default_related_name": "tickets",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("performance", "zone", "row", "seat"),
                        name="unique_performance_zone_row_seat",
                    )
                ],
            },
        ),
    ]
