# Generated by Django 5.2.1 on 2025-05-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="price",
        ),
    ]
