# Generated by Django 5.2.1 on 2025-05-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_remove_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
