# Generated by Django 5.2.1 on 2025-05-14 19:01

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0005_alter_genre_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="poster",
            field=models.ImageField(
                null=True, upload_to=theatre.models.play_image_path
            ),
        ),
    ]
